### ISSUE TITLE
CSS issues with Settings screen.

### ISSUE THREAD

**Issue by mvastarelli** [bitcobblers/multiminer-redux#1]
There are two rendering issues with the settings screen:

## Coin Strategy lightbulb alignment

When the coin strategy is set to `Skynet` the lightbulb renders to the right of the drop-down as it should, but when it is set to `Normal` it is rendered on the next line.

## Status Bar Clipping

The status bar at the bottom of the screen clips most of the screen elements as it should, however the headers for text boxes don't appear to be clipped. In the attached example, the header "RandomX *" renders even though it should be clipped.

## Reference Image

<img width="785" alt="image" src="https://github.com/bitcobblers/multiminer-redux/assets/5205466/80a8585f-ae2a-4786-9a20-53ce5547c06b">

**Comment by evan-cohen** [comment]
PR #2 addresses "Status Bar Clipping", but I wasn't able to repro "Coin Strategy lightbulb alignment":

<img width="1136" alt="image" src="https://github.com/bitcobblers/multiminer-redux/assets/25253818/d6448b09-b666-42b3-a36f-17501576093b">

**Comment by mvastarelli** [comment]
> PR #2 addresses "Status Bar Clipping", but I wasn't able to repro "Coin Strategy lightbulb alignment":
> 
> <img alt="image" width="1136" src="https://private-user-images.githubusercontent.com/25253818/335824366-d6448b09-b666-42b3-a36f-17501576093b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzg3MTksIm5iZiI6MTcxNzMzODQxOSwicGF0aCI6Ii8yNTI1MzgxOC8zMzU4MjQzNjYtZDY0NDhiMDktYjY2Ni00MmIzLWEzNmYtMTc1MDE1NzYwOTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDE0MjY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmZWY0YTUzNDljMWUwZDg5NjIwNThhZjM4MGFjOTg3NDViYTUwNmFiZTE2ZmEzMWZiNDVmZDczZmI3Y2JmODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8D5tlJYkeV0RGySy87-ruYewwssc4I3dvorrwOPExeU">

Can you try running it in a windows environment?  Maybe it's an issue with Edge.

**Comment by mvastarelli** [comment]
This was fixed during the settings screen redesign.
